### ISSUE TITLE
Update py-evm / web3 dependencies

### ISSUE THREAD

**Issue by cducrest** [voith/eth-tester-rpc#42]
Update dependencies of `eth-tester[py-evm]` and `web3` if possible. Notably to fix vulnerability in `cryptography<3.2` (https://github.com/advisories/GHSA-hggm-jpg3-v476) in currently required version of `eth-tester[py-evm]`

**Comment by voith** [comment]
Thanks for the report. I'll look into this tomorrow.

**Comment by voith** [comment]
fixed in v0.5.0-beta.1.
